language: java
jdk:
  - openjdk8
before_install:
  - pip install --user codecov
after_success:
  - codecov
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_deploy:
  - git config --local user.name "Jacek Spólnik"
  - git config --local user.email "jacek.spolnik@gmail.com"
deploy:
  provider: script
  script: ./gradlew release -Prelease.useAutomaticVersion=true
  skip_cleanup: true
  on:
    branch: master